### ISSUE TITLE
Base class Exception could be more specific (`throw new Exception(responseBody)`)

### ISSUE THREAD

**Issue by robfe** [merge-api/merge-csharp-client#27]
I don't think the [following code](https://github.com/merge-api/merge-csharp-client/blob/main/src/Merge.Client/Ats/Jobs/JobsClient.cs#L175C9-L180C43) is very helpful for real error handling scenarios:
```c#
string responseBody = await response.Raw.Content.ReadAsStringAsync();
if (response.StatusCode >= 200 && response.StatusCode < 400)
{
    return JsonSerializer.Deserialize<PaginatedScreeningQuestionList>(responseBody);
}
throw new Exception(responseBody);
```

It's impossible to tell what caused the exception when Exception is already the base class for all exceptions. Also, the status code is no longer available for inspection

Actually, I've just spotted in your docs that there is already an improvement in the works, very aligned with what I was hoping for: https://github.com/merge-api/merge-csharp-client?tab=readme-ov-file#exception-handling

When will that documentation become true?

**Comment by dsinghvi** [comment]
@robfe this is now supported as well ([link](https://github.com/merge-api/merge-csharp-client/blob/a35417c8ea2d6f68f8bfc76b271eb8e4ab30094e/src/Merge.Client/Crm/AssociationTypes/AssociationTypesClient.cs#L95-L111))
