### ISSUE TITLE
Allow API call cancellation with CancellationTokens

### ISSUE THREAD

**Issue by robfe** [merge-api/merge-csharp-client#28]
A typical async API in dotnet will optionally provide the ability to pass in a cancellation token - is this something you'll consider supporting?

Happy to help if you're keen!

**Comment by dsinghvi** [comment]
@robfe great idea, this is something that has been requested by a couple different consumers. We will plan to support this, ccing @dcb6 as well

**Comment by dsinghvi** [comment]
@robfe this is now supported in the latest SDK
