### ISSUE TITLE
DateTime Conversion to ISO 8601 Compliant Format 

### ISSUE THREAD

**Issue by travis-hervey-pi** [merge-api/merge-csharp-client#30]
In the various places where DateTime is being converted to ISO 8601 formats, the format string is wrong and results in an API error when trying to filter by the times.

**Example:**
https://github.com/merge-api/merge-csharp-client/blob/c03fb3311b8db48276b11b7ab9d4081caf0bb68c/src/Merge.Client/Hris/Employees/EmployeesClient.cs#L94

The above line produces `"oO"` as the time.

![image](https://github.com/user-attachments/assets/616025a6-911a-4116-840d-8de8eba9e086)

**Proposed Solution:**

The format string should be `"0"` which produces the ISO 8601 compliant time format.

```csharp
_query["modified_after"] = request.ModifiedAfter.Value.ToString("o");
``` 

This looks like it needs to be applied to all the Client objects where filtering by a DateTime is possible.

**Comment by dsinghvi** [comment]
@travis-hervey-pi -- we are currently working on a fix for this. ccing @dcb6 to follow up here when a new SDK version is released.

**Comment by stellis** [comment]
@dsinghvi @dcb6 This is an enormous bug with what looks like a 2-min fix, but it's been open for four months. It makes this package look essentially unmaintained and doesn't inspire confidence in using it in production.

**Comment by dsinghvi** [comment]
@stellis @travis-hervey-pi this has been resolved on the latest version of the SDK and the fix has been live for 2 months (link: https://github.com/merge-api/merge-csharp-client/blob/a35417c8ea2d6f68f8bfc76b271eb8e4ab30094e/src/Merge.Client/Hris/Employees/EmployeesClient.cs#L38-L41) 

Apologies for not commenting here sooner and if you have anymore issues, please let us know!
