### ISSUE TITLE
We can't find the MergeClient class in the NuGet package 

### ISSUE THREAD

**Issue by joseacta** [merge-api/merge-csharp-client#5]
It seems it isn't in the source code either. Maybe I'm missing something?

**Comment by dsinghvi** [comment]
@joseacta Will follow up here, thanks for reporting the issue.

**Comment by dsinghvi** [comment]
Hey @igrosu-LMS @joseacta -- we've regenerated the SDK [here](https://github.com/merge-api/merge-csharp-client/pull/6). Apologize for the inconvenience, feel free to vet the code and you should see implementations coming through now. 

This pull-request will be published as version `0.0.3`.
