### ISSUE TITLE
System.InvalidOperationException: 'An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.'

### ISSUE THREAD

**Issue by jmawebtech** [merge-api/merge-csharp-client#7]
I receive this error:

System.InvalidOperationException: 'An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.'

Here is my code:

Merge.Client.Merge merge = new Merge.Client.Merge(
  "OMIT", "OMIT"
);

            var items = await merge.Accounting.Items.ListAsync(new Merge.Client.Accounting.ItemsListRequest()
            {
                CreatedAfter = DateTime.Now.AddDays(-1),
                CreatedBefore = DateTime.Now.AddDays(1)
            });

Let me know next steps.

**Comment by dsinghvi** [comment]
@jmawebtech thanks for filing this issue, we are on it!

**Comment by jmawebtech** [comment]
I also tried

            Merge.Client.Merge merge = new Merge.Client.Merge(
  "OMIT", "OMIT", new Merge.Client.ClientOptions() {  BaseUrl = "https://api.merge.dev" }
);

when I call var Items, I get System.Exception was thrown.

**Comment by dsinghvi** [comment]
@jmawebtech we've root caused the issue and will be shipping a new SDK version tonight

**Comment by jmawebtech** [comment]
OK please respond when the package is available on Github.

**Comment by dsinghvi** [comment]
@jmawebtech version `0.0.6` has been published [here](https://www.nuget.org/packages/Merge.Client)!
